DROP TABLE account;
CREATE TABLE account(
id VARCHAR(30) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
balance INTEGER DEFAULT 0 ,
TYPE VARCHAR(20),
grade VARCHAR(20));

CREATE TABLE member(
id VARCHAR(30) PRIMARY KEY,
NAME VARCHAR(50) NOT null,
PASSWORmemberD VARCHAR(50),
email varchar(50),
address VARCHAR(50)
);