DROP TABLE account;
CREATE TABLE account(
id VARCHAR(30) PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
balance INTEGER DEFAULT 0 ,
TYPE VARCHAR(20),
grade VARCHAR(20));

DROP TABLE member;
CREATE TABLEmember member(
id VARCHAR(30) PRIMARY KEY,
NAME VARCHAR(50) NOT null,
PASSWORD VARCHAR(20),
email varchar(50),
address VARCHAR(200)
);